// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Route struct {
	ID                   uuid.UUID       `json:"id"`
	DriverID             uuid.UUID       `json:"driver_id"`
	VehicleID            uuid.UUID       `json:"vehicle_id"`
	OriginLat            float64         `json:"origin_lat"`
	OriginLng            float64         `json:"origin_lng"`
	DestinationLat       float64         `json:"destination_lat"`
	DestinationLng       float64         `json:"destination_lng"`
	OriginAddress        sql.NullString  `json:"origin_address"`
	DestinationAddress   sql.NullString  `json:"destination_address"`
	EstimatedDistanceKm  sql.NullFloat64 `json:"estimated_distance_km"`
	EstimatedDurationMin sql.NullFloat64 `json:"estimated_duration_min"`
	ActualDurationMin    sql.NullFloat64 `json:"actual_duration_min"`
	Status               string          `json:"status"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Vehicle struct {
	ID           uuid.UUID      `json:"id"`
	DriverID     uuid.UUID      `json:"driver_id"`
	LicensePlate string         `json:"license_plate"`
	Model        sql.NullString `json:"model"`
	ImageUrl     sql.NullString `json:"image_url"`
	Capacity     sql.NullInt32  `json:"capacity"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
