// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	// when the route is completed
	DeleteRoute(ctx context.Context, id uuid.UUID) error
	// returns the updated user
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteVehicle(ctx context.Context, id uuid.UUID) error
	GetRouteByID(ctx context.Context, id uuid.UUID) (Route, error)
	GetRoutesByDriverID(ctx context.Context, arg GetRoutesByDriverIDParams) ([]Route, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// returns the created user
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// returns the created vehicle
	GetVehicleByID(ctx context.Context, id uuid.UUID) (Vehicle, error)
	GetVehicleByLicensePlate(ctx context.Context, licensePlate string) (Vehicle, error)
	GetVehiclesByDriverID(ctx context.Context, arg GetVehiclesByDriverIDParams) ([]Vehicle, error)
	ListRoutesByDriverAndStatus(ctx context.Context, arg ListRoutesByDriverAndStatusParams) ([]Route, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateRouteActualDuration(ctx context.Context, arg UpdateRouteActualDurationParams) (Route, error)
	UpdateRouteStatus(ctx context.Context, arg UpdateRouteStatusParams) (Route, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPartial(ctx context.Context, arg UpdateUserPartialParams) (User, error)
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error)
}

var _ Querier = (*Queries)(nil)
