// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (id, driver_id, license_plate, model, image_url, capacity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, driver_id, license_plate, model, image_url, capacity, created_at, updated_at
`

type CreateVehicleParams struct {
	ID           uuid.UUID      `json:"id"`
	DriverID     uuid.UUID      `json:"driver_id"`
	LicensePlate string         `json:"license_plate"`
	Model        sql.NullString `json:"model"`
	ImageUrl     sql.NullString `json:"image_url"`
	Capacity     sql.NullInt32  `json:"capacity"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, createVehicle,
		arg.ID,
		arg.DriverID,
		arg.LicensePlate,
		arg.Model,
		arg.ImageUrl,
		arg.Capacity,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.LicensePlate,
		&i.Model,
		&i.ImageUrl,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles WHERE id = $1
`

func (q *Queries) DeleteVehicle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVehicle, id)
	return err
}

const getVehicleByID = `-- name: GetVehicleByID :one

SELECT id, driver_id, license_plate, model, image_url, capacity, created_at, updated_at FROM vehicles WHERE id = $1
`

// returns the created vehicle
func (q *Queries) GetVehicleByID(ctx context.Context, id uuid.UUID) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, getVehicleByID, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.LicensePlate,
		&i.Model,
		&i.ImageUrl,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleByLicensePlate = `-- name: GetVehicleByLicensePlate :one
SELECT id, driver_id, license_plate, model, image_url, capacity, created_at, updated_at FROM vehicles WHERE license_plate = $1
`

func (q *Queries) GetVehicleByLicensePlate(ctx context.Context, licensePlate string) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, getVehicleByLicensePlate, licensePlate)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.LicensePlate,
		&i.Model,
		&i.ImageUrl,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleWithDriver = `-- name: GetVehicleWithDriver :one
SELECT 
    v.id AS vehicle_id,
    v.driver_id,
    v.license_plate,
    v.model,
    v.image_url,
    v.capacity,
    v.created_at AS vehicle_created_at,
    v.updated_at AS vehicle_updated_at,
    u.id AS driver_id,
    u.name AS driver_name,
    u.email AS driver_email,
    u.created_at AS driver_created_at
FROM vehicles v
JOIN users u ON v.driver_id = u.id
WHERE v.id = $1
`

type GetVehicleWithDriverRow struct {
	VehicleID        uuid.UUID      `json:"vehicle_id"`
	DriverID         uuid.UUID      `json:"driver_id"`
	LicensePlate     string         `json:"license_plate"`
	Model            sql.NullString `json:"model"`
	ImageUrl         sql.NullString `json:"image_url"`
	Capacity         sql.NullInt32  `json:"capacity"`
	VehicleCreatedAt sql.NullTime   `json:"vehicle_created_at"`
	VehicleUpdatedAt sql.NullTime   `json:"vehicle_updated_at"`
	DriverID_2       uuid.UUID      `json:"driver_id_2"`
	DriverName       string         `json:"driver_name"`
	DriverEmail      string         `json:"driver_email"`
	DriverCreatedAt  time.Time      `json:"driver_created_at"`
}

func (q *Queries) GetVehicleWithDriver(ctx context.Context, id uuid.UUID) (GetVehicleWithDriverRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicleWithDriver, id)
	var i GetVehicleWithDriverRow
	err := row.Scan(
		&i.VehicleID,
		&i.DriverID,
		&i.LicensePlate,
		&i.Model,
		&i.ImageUrl,
		&i.Capacity,
		&i.VehicleCreatedAt,
		&i.VehicleUpdatedAt,
		&i.DriverID_2,
		&i.DriverName,
		&i.DriverEmail,
		&i.DriverCreatedAt,
	)
	return i, err
}

const getVehiclesByDriverID = `-- name: GetVehiclesByDriverID :many
SELECT id, driver_id, license_plate, model, image_url, capacity, created_at, updated_at FROM vehicles WHERE driver_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetVehiclesByDriverIDParams struct {
	DriverID uuid.UUID `json:"driver_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) GetVehiclesByDriverID(ctx context.Context, arg GetVehiclesByDriverIDParams) ([]Vehicle, error) {
	rows, err := q.db.QueryContext(ctx, getVehiclesByDriverID, arg.DriverID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.LicensePlate,
			&i.Model,
			&i.ImageUrl,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET 
    model = COALESCE($2, model),
    image_url = COALESCE($3, image_url),
    capacity = COALESCE($4, capacity),
    updated_at = NOW()
WHERE id = $1
RETURNING id, driver_id, license_plate, model, image_url, capacity, created_at, updated_at
`

type UpdateVehicleParams struct {
	ID       uuid.UUID      `json:"id"`
	Model    sql.NullString `json:"model"`
	ImageUrl sql.NullString `json:"image_url"`
	Capacity sql.NullInt32  `json:"capacity"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, updateVehicle,
		arg.ID,
		arg.Model,
		arg.ImageUrl,
		arg.Capacity,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.LicensePlate,
		&i.Model,
		&i.ImageUrl,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
